### PR TITLE
update to nestjs6

### PR DESCRIPTION
**Pull request by FSM1**

### CODE REVIEW

**Comment by spike008t** [comment]
Sorry for the delay, thank you very much I'll integrate your PR once you update the review.

**Comment by FSM1** [comment]
> Sorry for the delay, thank you very much I'll integrate your PR once you update the review.

Just noticed that some of the changes I made to the package.json have also pulled through to this repo. Will fix that quickly.

**Comment by spike008t** [comment]
I close the PR, I've done on update to nestjs v6 on master branch. I've also added your name on the package.json.

Thank.

**Comment by FSM1** [comment]
thank you sir, much appreciated

**Pull request closed without merging**
