### PR TITLE
Refactor/metrics services

### PR DESCRIPTION
**Pull request by spike008t**
Remove the old declaration counters stuff on modules in order to simplify the counter declaration.

## TODO

- [x] Update documentation
- [x] Supports
  - [x] nestjs v6
  - [x] nestjs v7
- [x] Tests
  - [x] e2e

### CODE REVIEW

**Comment by atjeff** [comment]
Any movement on this one?

**Comment by gperdomor** [comment]
Please merge this 🙏🏽

**Comment by robbiet480** [comment]
@digikare Mind merging this?

**Comment by derbl4ck** [comment]
this would be 🐱‍🏍

**Comment by spike008t** [comment]
Yes sorry for the delay, I will merge it this week :)

**Pull request merged**
